### ISSUE TITLE
ValueError when encountering XML comments (using lxml)

### ISSUE THREAD

**Issue by ghost** [Morgan-Stanley/pyfixmsg#3]
Unlike xml.etree.ElementTree.parse(), lxml.etree.parse() reads XML comments and stores them as lxml.etree._Comment objects, with tag == lxml.etree.Comment (the function which creates lxml.etree._Comment objects). This results in the error below:

Traceback (most recent call last):
  File "./error_example.py", line 32, in <module>
    main()
  File "./error_example.py", line 16, in main
    spec = FixSpec('FIXFX.xml')
  File "../pyfixmsg/reference.py", line 164, in __init__
    (MessageType(e, self) for e in self.tree.findall('messages/message'))}
  File "../pyfixmsg/reference.py", line 163, in <dictcomp>
    self.msg_types = {m.msgtype.encode('ascii'): m for m in
  File "../pyfixmsg/reference.py", line 164, in <genexpr>
    (MessageType(e, self) for e in self.tree.findall('messages/message'))}
  File "../pyfixmsg/reference.py", line 278, in __init__
    self.composition = _extract_composition(element, spec)
  File "../pyfixmsg/reference.py", line 198, in _extract_composition
    raise ValueError("Could not process element '{}'".format(elem.tag))
ValueError: Could not process element '\<built-in function Comment\>'

**Comment by ghost** [comment]
Fix will be applied by MS OSS team.
